mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = "common"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from news.views import base_views as views_news

urlpatterns = [
    path("", views_news.index),
    path("admin/", admin.site.urls),
    path("common/", include("common.urls")),
    path("news/", include("news.urls")),
]

mysite/news/urls.py
from django.urls import path
from .views import base_views, keyword_views, site_views

app_name = "news"

urlpatterns = [
    path("", base_views.index, name="index"),
    path("search/", base_views.news_search, name="news_search"),
    path("keyword/", keyword_views.KeywordList.as_view(), name="keyword_list"),
    path(
        "keyword/create/", keyword_views.KeywordCreate.as_view(), name="keyword_create"
    ),
    path(
        "keyword/update/<int:pk>/",
        keyword_views.KeywordUpdate.as_view(),
        name="keyword_update",
    ),
    path(
        "keyword/delete/<int:pk>/",
        keyword_views.KeywordDelete.as_view(),
        name="keyword_delete",
    ),
    path("site/create/", site_views.SiteCreate.as_view(), name="site_create"),
    path("site/update/<int:pk>/", site_views.SiteUpdate.as_view(), name="site_update"),
]

mysite/news/models.py
from django.db import models
from django.contrib.auth.models import User


class Keyword(models.Model):
    title = models.CharField(max_length=50, verbose_name="관리명", unique=False)
    content = models.CharField(max_length=100, verbose_name="키워드")
    mailing = models.BooleanField(default=False, verbose_name="메일발송")
    order = models.PositiveIntegerField(unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["order"]
        constraints = [
            models.UniqueConstraint(
                fields=["title", "author"], name="unique_title_author"
            )
        ]


class Site(models.Model):
    address = models.CharField(max_length=100, verbose_name="Address")
    description = models.CharField(max_length=100, verbose_name="Description")

    def __str__(self):
        return self.description

mysite/news/forms.py
from django import forms


class NewsSearchForm(forms.Form):
    keyword = forms.CharField(max_length=100, required=True)

mysite/common/views.py
from django.shortcuts import render

# Create your views here.

mysite/news/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormView
from .forms import NewsSearchForm
from .utils import naverapi_utils as naver_api


@login_required(login_url="common:login")
def index(request):
    """
    뉴스 검색 화면으로 리다이렉트한다.
    """
    return redirect("news:news_search")


@login_required(login_url="common:login")
def news_search(request):
    """
    뉴스 검색 화면을 반환한다.
    """

    news_list = None

    if request.method == "GET":
        if len(request.GET):
            form = NewsSearchForm(request.GET)

            if form.is_valid():
                keyword = form.cleaned_data["keyword"]
                news_list = naver_api.get_news_by_hour(keyword)
        # 뉴스를 검색하지 않고 검색 페이지를 오픈할 경우에는
        # 비어 있는 폼을 반환한다.
        else:
            form = NewsSearchForm()
    else:
        form = NewsSearchForm()

    return render(
        request,
        "news/news_search.html",
        {"form": form, "news_list": news_list},
    )

mysite/news/views/base_views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from ..models import Keyword
from ..forms import NewsSearchForm
from ..utils import naverapi_utils as naver_api


@login_required(login_url="common:login")
def index(request):
    """
    뉴스 검색 화면으로 리다이렉트한다.
    """
    return redirect("news:news_search")


@login_required(login_url="common:login")
def news_search(request):
    """
    뉴스 검색 화면을 반환한다.
    """

    news_list = None
    keywords = Keyword.objects.all()

    if request.method == "GET":
        if len(request.GET):
            form = NewsSearchForm(request.GET)

            if form.is_valid():
                keyword = form.cleaned_data["keyword"]
                news_list = naver_api.get_news_by_hour(keyword)
        # 뉴스를 검색하지 않고 검색 페이지를 오픈할 경우에는
        # 비어 있는 폼을 반환한다.
        else:
            form = NewsSearchForm()
    else:
        form = NewsSearchForm()

    return render(
        request,
        "news/news_search.html",
        {"form": form, "news_list": news_list, "keywords": keywords},
    )

mysite/news/views/keyword_views.py
from django.views.generic import ListView, CreateView
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.core.exceptions import PermissionDenied
from django.contrib.auth.decorators import login_required
from ..models import Keyword


class KeywordList(LoginRequiredMixin, ListView):
    """
    키워드 리스트를 반환한다.
    """

    login_url = "common:login"
    model = Keyword

    def get_queryset(self):
        current_user = self.request.user
        keyword_list = Keyword.objects.filter(author=current_user)

        return keyword_list


class KeywordCreate(LoginRequiredMixin, CreateView):
    """
    키워드를 생성한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:keyword_list")
    model = Keyword
    fields = ["title", "content", "mailing"]

    def form_valid(self, form):
        keyword_last = Keyword.objects.last()
        if keyword_last:
            form.instance.order = keyword_last.pk + 1
        else:
            form.instance.order = 1

        current_user = self.request.user
        if current_user.is_authenticated:
            form.instance.author = current_user
            response = super(KeywordCreate, self).form_valid(form)

            return response
        else:
            return redirect("news:keyword_list")


class KeywordUpdate(LoginRequiredMixin, UpdateView):
    """
    키워드를 수정한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:keyword_list")
    model = Keyword
    fields = ["title", "content", "mailing"]

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(KeywordUpdate, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied


class KeywordDelete(LoginRequiredMixin, DeleteView):
    """
    키워드를 삭제한다.
    """

    login_url = "common:login"
    success_url = reverse_lazy("news:keyword_list")
    model = Keyword

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user == self.get_object().author:
            return super(KeywordDelete, self).dispatch(request, *args, **kwargs)
        else:
            raise PermissionDenied

mysite/news/views/site_views.py
from rest_framework import generics
from rest_framework.permissions import IsAuthenticated
from ..serializers import SiteSerializer
from ..models import Site


class SiteCreate(generics.CreateAPIView):
    """
    언론사를 생성한다.
    """

    serializer_class = SiteSerializer
    permission_classes = [IsAuthenticated]


class SiteUpdate(generics.UpdateAPIView):
    """
    언론사를 수정한다.
    """

    queryset = Site.objects.all()
    serializer_class = SiteSerializer
    permission_classes = [IsAuthenticated]

mysite/templates/base.html
{% load static %}

<!DOCTYPE html>

<html lang="ko" class="h-100">

<head>
    <meta charset="utf-8" />
    <meta name="viewport"
        content="width=device-width, initial-scale=1 minimum-scale=1, maximum-scale=1, user-scalable=no">

    <title>
        {% block title %}Jeby{% endblock title %}
    </title>

    <link rel="shortcut icon" href="{% static 'images/swallow_16px.png' %}" />
    <link rel="icon" sizes="152x152" href="{% static 'images/swallow_152px.png' %}" />

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Nanum+Gothic:wght@400;700&family=Noto+Sans+KR:wght@300;400;500&display=swap"
        rel="stylesheet">

    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap-5.0.2/css/bootstrap.min.css' %}" />

    {% block custom_css %}{% endblock custom_css %}
</head>

{% block body %}
{% endblock body %}

{% block script %}
<script src="https://kit.fontawesome.com/5b01bdb70e.js" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap/bootstrap-5.0.2/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'jquery/jquery-3.6.0/jquery-3.6.0.min.js' %}"></script>
{% endblock script %}

</html>

mysite/templates/base_news.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'news/css/base_news.css' %}" />
{% endblock custom_css %}

{% block body %}

<body class="d-flex flex-column h-100">
    {% include 'include/navbar.html' %}

    <div class="container" id="error_msg">
        <div class="row">
            <div class="col">
                {% include "include/form_errors.html" %}
            </div>
        </div>
    </div>

    <main class="h-100">
        {% block content %}
        {% endblock content %}
    </main>

    {% block footer %}
    {% include 'include/footer.html' %}
    {% endblock footer %}

</body>
{% endblock body %}

{% block script %}
{{ block.super }}

{% endblock script %}

mysite/templates/common/login.html
{% extends 'base.html' %}

{% load static %}

{% block custom_css %}
<link rel="stylesheet" href="{% static 'common/css/login.css' %}" />
{% endblock custom_css %}

{% block body %}

<body class="text-center">
    <div class="container">
        <div class="row">
            <div class="col">
                {% include "include/form_errors.html" %}
            </div>
        </div>
        <div class="row">
            <main class="form-signin">
                <form method="post" action="{% url 'common:login' %}">
                    {% csrf_token %}
                    <img class="mb-2" src="{% static 'images/swallow_152px.png' %}" alt="" width="120" height="120">
                    <div class="form-floating">
                        <input type="text" class="form-control" id="username" placeholder="ID" name="username"
                            value="{{ form.username.value|default_if_none:'' }}">
                        <label for="username">ID</label>
                    </div>
                    <div class="form-floating">
                        <input type="password" class="form-control" id="password" placeholder="Password" name="password"
                            value="{{ form.password.value|default_if_none:'' }}">
                        <label for="password">Password</label>
                    </div>
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Log in</button>
                    <p class="mt-5 mb-3 text-muted"></p>
                </form>
            </main>
        </div>
    </div>
</body>
{% endblock body %}

mysite/templates/include/footer.html
<footer class="footer mt-auto py-2 bg-light border-top border-1">
    <div class="container text-center">
        <span class="text-muted">@ 2021 future talented person</span>
    </div>
</footer>

mysite/templates/include/form_errors.html
{% if form.errors %}
{% for field in form %}
{% for error in field.errors %}
<div class="alert alert-danger" style="padding: 10px 16px">
    <strong>{{ field.label }}</strong>
    {{ error }}
</div>
{% endfor %}
{% endfor %}
{% for error in form.non_field_errors %}
<div class="alert alert-danger" style="padding: 10px 16px">
    <strong>{{ error }}</strong>
</div>
{% endfor %}
{% endif %}

mysite/templates/include/navbar.html
 {% load static %}

 <nav class="navbar navbar-expand-md navbar-light fixed-top bg-light border-bottom border-1 mb-0">
     <div class="container">
         <a class="navbar-brand" href="{% url 'news:news_search' %}">
             <img src="{% static 'images/swallow_152px.png' %}" alt="" height="31"
                 class="d-inline-block align-text-top">
             <span>Jeby</span>
         </a>
         <div class="collapse navbar-collapse" id="navbarSupportedContent">
             <ul class="navbar-nav me-auto">
                 <li class="nav-item">
                     <a class="nav-link" aria-current="page" href="{% url 'news:news_search' %}">뉴스검색</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" aria-current="page" href="{% url 'news:keyword_list' %}">키워드관리</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" aria-current="page" href="#">수신자관리</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link" aria-current="page" href="#">이메일설정</a>
                 </li>
             </ul>
         </div>
         <form class="d-flex">
             {% csrf_token %}
             <button class="navbar-toggler me-2" type="button" data-bs-toggle="collapse"
                 data-bs-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent"
                 aria-expanded="false" aria-label="Toggle navigation" id="toggle-button">
                 <span class="navbar-toggler-icon"></span>
             </button>
             {% if user.is_authenticated %}
             <a href="{% url 'common:logout' %}" class="btn btn-outline-secondary nav-button me-2" type="button">
                 logout
             </a>
             {% endif %}
         </form>
     </div>
     <div class="collapse navbar-toggler p-0 mt-2 w-100 border-bottom-0" id="navbarToggleExternalContent">
         <div class="py-2 px-3">
             <div class="nav-item-mobile"><a href="{% url 'news:news_search' %}">뉴스검색</a></div>
             <div class="nav-item-mobile"><a href="{% url 'news:keyword_list' %}">키워드관리</a></div>
             <div class="nav-item-mobile"><a href="#">수신자관리</a></div>
             <div class="nav-item-mobile"><a href="#">이메일설정</a></div>
         </div>
     </div>
 </nav>

mysite/templates/news/keyword_form.html
{% extends 'base_news.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block custom_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'news/css/keyword_form.css' %}" />
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="title" class="form-label">관리명</label>
                    <input type="text" class="form-control" id="title" name="title"
                        value="{{ form.title.value|default_if_none:'' }}">
                </div>
                <div class="mb-3">
                    <label for="content" class="form-label">키워드</label>
                    <input class="form-control" id="content" name="content"
                        value="{{ form.content.value|default_if_none:'' }}">
                </div>
                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" id="mailing" name="mailing"
                        {% if form.mailing.value %}checked{% endif %}>
                    <label class="form-check-label" for="mailing">
                        메일발송
                    </label>
                </div>
                <div class="float-end">
                    <a href="{% url 'news:keyword_list' %}" type="button" class="btn btn-outline-secondary"
                        id="btn-list">목록</a>
                    <button type="sumit" class="btn btn-primary">저장</button>
                    {% if keyword %}
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal"
                        data-bs-target="#deleteKeywordModal">삭제
                    </button>
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>

{% if keyword %}
<div class="modal fade" id="deleteKeywordModal" tabindex="-1" aria-labelledby="deleteKeywordModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <form method="post" action="{% url 'news:keyword_delete' keyword.id %}">
                {% csrf_token %}
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">삭제하기</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    정말 삭제하시겠습니까?
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    {% if keyword %}
                    <input type="submit" class="btn btn-danger" value="Delete">
                    {% endif %}
                </div>
            </form>
        </div>
    </div>
</div>
{% endif %}
{% endblock content %}

{% block script %}
{{ block.super }}
<script src="{% static 'news/js/keyword_form.js' %}"></script>
{% endblock script %}

mysite/templates/news/keyword_list.html
{% extends 'base_news.html' %}

{% load static %}

{% block custom_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'news/css/keyword_list.css' %}" />
{% endblock custom_css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col">
            <div class="d-flex flex-row-reverse mb-2">
                <a href="{% url 'news:keyword_create' %}" type="button" class="btn btn-primary">등록</a>
            </div>
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="width: 30%">관리명</th>
                            <th scope="col">키워드</th>
                            <th scope="col" style="width: 10%">메일</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for keyword in keyword_list %}
                        <tr>
                            <td scope="row">
                                <a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.title }}</a>
                            </td>
                            <td>
                                <a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.content }}</a>
                            </td>
                            <td>
                                <a href="{% url 'news:keyword_update' keyword.id %}">{{ keyword.mailing }}</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
{{ block.super }}
<script src="{% static 'news/js/keyword_list.js' %}"></script>
{% endblock script %}

mysite/templates/news/news_search.html
{% extends 'base_news.html' %}

{% load static %}

{% block custom_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'news/css/news_search.css' %}" />
{% endblock custom_css %}

{% block content %}
<div class="container" id="search-box">
    <form action="" method="get" id="frm-search">
        <div class="d-flex flex-column">
            {% if not form.keyword.value %}
            <div class="row mb-1">
                <div class="col text-center">
                    <p class="h4" id="search-title">뉴스 검색 키워드를 입력하세요.</p>
                </div>
            </div>
            {% endif %}

            <div class="row" style="padding-bottom:16px;">
                <div class="col">
                    <div class="card border-secondary shadow-sm">
                        <div class="card-body" id="keyword-box">
                            <div class="d-flex flex-row">
                                <button type="button" class="btn btn-secondary" id="btn-keyword-group"
                                    data-bs-toggle="modal" data-bs-target="#keywordListModal">키워드</button>
                                <div class="flex-grow-1">
                                    <input type="text" class="form-control" name="keyword" id="input-keyword"
                                        value="{{ form.keyword.value|default_if_none:'' }}" autocomplete=off>
                                </div>
                                <div class="me-2">
                                    <a href="#"><span id="search-img"><i class="fas fa-search"></i></span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>

    {% if form.keyword.value %}
    <div class="row mb-3">
        <div class="col">
            <div class="card">
                <div class="card-header">
                    검색뉴스 ({{ news_list|length }}건)
                </div>
                <div class="card-body py-2">
                    {% if news_list %}
                    {% for news in news_list %}
                    <div class="news-item fs-6" id="news-{{ forloop.counter }}">
                        <span class="check-sitename me-2">
                            <i class="bi bi-square"></i>
                        </span>
                        <span class="box-sitename me-2">
                            {% if news.sitename == '' %}
                            <a href="#" style="font-weight:100; color:#D9C3CE" data-bs-toggle="modal"
                                data-bs-target="#siteEditModal" data-siteuri="{{ news.siteuri }}" data-sitename=""
                                data-action-url="{% url 'news:site_create' %}" data-action-type="create"
                                data-sitename="">
                                등록하기</a>
                            {% else %}
                            <a href="#" data-bs-toggle="modal" data-bs-target="#siteEditModal"
                                data-siteuri="{{ news.siteuri }}" data-sitename="{{ news.sitename }}"
                                data-action-url="{% url 'news:site_update' news.siteid %}" data-action-type="update"
                                data-sitename="{{ news.sitename }}">
                                {{ news.sitename }}</a>
                            {% endif %}
                        </span>
                        <a href="{{ news.originallink }}" target="_blank">
                            <span class="news-title" style="font-weight:400;">
                                {{ news.title|safe|truncatechars:50 }}
                            </span>
                        </a>
                        <span class="badge bg-light text-dark">
                            {{ news.pubDate|date:"Y/m/d H:i:s" }}
                        </span>
                    </div>
                    {% endfor %}
                    {% else %}
                    검색된 뉴스가 없습니다.
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    {% endif %}
</div>

<div class="modal fade" id="keywordListModal" tabindex="-1" aria-labelledby="keywordListModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="keywordListModalLabel">키워드 선택하기</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col" style="width:30%;">관리명</th>
                            <th scope="col">키워드</th>
                            <th scope="col" style="width:20%;">액션</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for keyword in keywords %}
                        <tr>
                            <td>{{ keyword.title }}</td>
                            <td>{{ keyword.content }}</td>
                            <td>
                                <button type="button" class="btn btn-sm btn-primary btn-select-keyword"
                                    data-keyword="{{ keyword.content }}">선택</button>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="siteEditModal" tabindex="-1" aria-labelledby="siteEditModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <form id="frmSiteEditModeal" action="">
                <div class="modal-header">
                    <h5 class="modal-title" id="siteEditModalLabel">언론사 관리하기</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label for="modal-siteuri" class="form-label">Address</label>
                        <input type="text" class="form-control" id="modal-siteuri" disabled readonly>
                    </div>
                    <div class="mb-2">
                        <label for="modal-sitedesc" class="form-label">Description</label>
                        <input type="text" class="form-control" id="modal-sitedesc" autocomplete=off>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="btnSaveSiteEditModal">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

{% block footer %}
{% endblock footer %}

{% block script %}
{{ block.super }}
<script src="{% static 'news/js/news_search.js' %}"></script>
{% endblock script %}